"""
main.py  –  Car Park Detection (Hot-Wheel / Small Car Optimised)
================================================================
Usage:
    python main.py                   # webcam (index 0)
    python main.py carPark.mp4       # video file
    python main.py 1                 # secondary webcam

Requires:  parking_config.pkl  (generated by calibration.py)

Controls (runtime):
    Q / ESC      → quit
    D            → toggle debug view (adaptive-threshold overlay)
    +  /  -      → raise / lower sensitivity on the fly (±10)
    S            → save current sensitivity back to config

Detection pipeline (mirrors reference project):
    BGR → Grayscale → Gaussian Blur → Adaptive Threshold →
    Median Blur → Dilation  →  countNonZero per zone
    count < sensitivity  →  FREE  (green)
    count ≥ sensitivity  →  OCCUPIED  (red)

Hot-wheel specific tuning:
    • Zones sized to match the car footprint in calibration
    • Contour pre-screen rejects ambient noise blobs that
      are too small or too large relative to the zone area
    • Per-zone threshold is computed relative to zone area
      so differently-sized zones are all compared fairly
"""

import cv2
import pickle
import numpy as np
import sys
import os
import time

# ─────────────────────────────────────────────────────────────────────────────
CONFIG_FILE = "parking_config.pkl"
WIN_MAIN    = "Car Park Detection"
WIN_DEBUG   = "Debug – Processed Frame"

# Colour palette
C_FREE      = (0,   230,  0  )
C_OCC       = (0,   0,   230 )
C_YEL       = (0,   240, 240 )
C_WHT       = (230, 230, 230 )
C_PANEL     = (20,  20,  20  )
C_ACCENT    = (100, 180, 255 )

# ─────────────────────────────────────────────────────────────────────────────
def load_config() -> dict:
    if not os.path.exists(CONFIG_FILE):
        raise FileNotFoundError(
            f"'{CONFIG_FILE}' not found – run calibration.py first."
        )
    with open(CONFIG_FILE, "rb") as f:
        return pickle.load(f)


def save_sensitivity(cfg: dict, sensitivity: int):
    cfg["sensitivity"] = sensitivity
    with open(CONFIG_FILE, "wb") as f:
        pickle.dump(cfg, f)
    print(f"[SAVED] Sensitivity {sensitivity} → {CONFIG_FILE}")


# ─────────────────────────────────────────────────────────────────────────────
# Image processing pipeline
# ─────────────────────────────────────────────────────────────────────────────

def preprocess(frame: np.ndarray) -> np.ndarray:
    """
    Convert BGR frame to a binary edge/feature map.
    Empty pavement → few white pixels; car → many white pixels.
    """
    gray    = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    blur    = cv2.GaussianBlur(gray, (3, 3), 1)
    thresh  = cv2.adaptiveThreshold(
                  blur, 255,
                  cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                  cv2.THRESH_BINARY_INV,
                  25, 16)
    median  = cv2.medianBlur(thresh, 5)
    kernel  = np.ones((3, 3), np.uint8)
    dilated = cv2.dilate(median, kernel, iterations=1)
    return dilated


def zone_has_car(crop_proc: np.ndarray,
                 zone_w: int, zone_h: int,
                 sensitivity: int) -> tuple[bool, int]:
    """
    Returns (occupied: bool, pixel_count: int).

    Two-stage check:
      1. Raw non-zero count threshold (same as reference project).
      2. Contour sanity check: at least one contour whose area is
         between 5 % and 95 % of the zone area must exist, which
         rejects single-pixel noise or a full-frame glitch.
    """
    count = cv2.countNonZero(crop_proc)

    # Stage 1 – quick pixel count gate
    if count < sensitivity:
        return False, count                     # definitely empty

    # Stage 2 – contour plausibility (hot-wheel tuning)
    zone_area = zone_w * zone_h
    lo_area   = zone_area * 0.04              # minimum contour: 4 % of zone
    hi_area   = zone_area * 0.96             # maximum contour: 96 % of zone

    cnts, _ = cv2.findContours(crop_proc, cv2.RETR_EXTERNAL,
                                cv2.CHAIN_APPROX_SIMPLE)
    plausible = any(lo_area < cv2.contourArea(c) < hi_area for c in cnts)

    return plausible, count


# ─────────────────────────────────────────────────────────────────────────────
# Drawing helpers
# ─────────────────────────────────────────────────────────────────────────────

def draw_zones(frame: np.ndarray,
               processed: np.ndarray,
               spaces: dict,
               sensitivity: int) -> tuple[int, int]:
    """
    Draw coloured rectangles over each parking zone.
    Returns (free_count, total_count).
    """
    free = 0

    for name, (x, y, w, h) in spaces.items():
        # Guard against zones that exceed frame boundaries
        fh, fw = processed.shape[:2]
        x  = max(0, min(x, fw - 1))
        y  = max(0, min(y, fh - 1))
        x2 = min(x + w, fw)
        y2 = min(y + h, fh)
        if x2 <= x or y2 <= y:
            continue

        crop  = processed[y:y2, x:x2]
        occ, count = zone_has_car(crop, x2 - x, y2 - y, sensitivity)

        if occ:
            color, thick = C_OCC, 2
            status       = "OCC"
        else:
            color, thick = C_FREE, 3
            status       = "FREE"
            free         += 1

        cv2.rectangle(frame, (x, y), (x + w, y + h), color, thick)

        # Space name label (top-left of zone)
        cv2.putText(frame, name.upper(),
                    (x + 3, y + 14),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.48, C_YEL, 1, cv2.LINE_AA)

        # Pixel count (bottom of zone)
        cv2.putText(frame, str(count),
                    (x + 3, y + h - 4),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.38, color, 1, cv2.LINE_AA)

    return free, len(spaces)


def draw_status_bar(frame: np.ndarray,
                    free: int, total: int,
                    sensitivity: int,
                    fps: float,
                    debug: bool):
    """Semi-transparent status banner at the top of the frame."""
    h, w = frame.shape[:2]
    overlay = frame.copy()
    cv2.rectangle(overlay, (0, 0), (w, 62), C_PANEL, -1)
    cv2.addWeighted(overlay, 0.65, frame, 0.35, 0, frame)

    occ   = total - free
    bar_c = C_FREE if free > 0 else C_OCC

    cv2.putText(frame, f"FREE: {free}/{total}",
                (16, 44), cv2.FONT_HERSHEY_SIMPLEX,
                1.2, bar_c, 2, cv2.LINE_AA)

    info = (f"OCC:{occ}  SENS:{sensitivity}  FPS:{fps:.1f}"
            f"  [D] debug={'ON' if debug else 'OFF'}  [+/-] tune  [Q] quit")
    cv2.putText(frame, info,
                (280, 44), cv2.FONT_HERSHEY_SIMPLEX,
                0.48, C_WHT, 1, cv2.LINE_AA)


def draw_debug_overlay(processed: np.ndarray,
                       spaces: dict,
                       sensitivity: int) -> np.ndarray:
    """Return a colour-coded version of the processed frame for debugging."""
    debug = cv2.cvtColor(processed, cv2.COLOR_GRAY2BGR)
    for name, (x, y, w, h) in spaces.items():
        fh, fw = processed.shape[:2]
        x2 = min(x + w, fw)
        y2 = min(y + h, fh)
        crop  = processed[y:y2, x:x2]
        count = cv2.countNonZero(crop)
        c = C_OCC if count >= sensitivity else C_FREE
        cv2.rectangle(debug, (x, y), (x + w, y + h), c, 2)
        cv2.putText(debug, name.upper(), (x + 2, y + 14),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.45, C_YEL, 1, cv2.LINE_AA)
    return debug


# ─────────────────────────────────────────────────────────────────────────────
def main():
    # ── load config ──────────────────────────────────────────────────────────
    try:
        cfg = load_config()
    except FileNotFoundError as e:
        print(f"[ERROR] {e}")
        return

    spaces      : dict = cfg.get("spaces", {})
    sensitivity : int  = cfg.get("sensitivity", 900)

    if not spaces:
        print("[ERROR] No parking spaces in config. Run calibration.py first.")
        return

    print(f"[READY] {len(spaces)} spaces | sensitivity={sensitivity}")

    # ── open video source ─────────────────────────────────────────────────────
    source = sys.argv[1] if len(sys.argv) > 1 else 0
    try:
        source = int(source)
    except (ValueError, TypeError):
        pass

    cap = cv2.VideoCapture(source)
    if not cap.isOpened():
        print(f"[ERROR] Cannot open source: {source!r}")
        return

    debug_mode = False
    t_prev     = time.time()
    fps        = 0.0

    cv2.namedWindow(WIN_MAIN, cv2.WINDOW_NORMAL)

    # ── main loop ─────────────────────────────────────────────────────────────
    while True:
        # Loop video when it ends
        if cap.get(cv2.CAP_PROP_FRAME_COUNT) > 0:
            if cap.get(cv2.CAP_PROP_POS_FRAMES) >= cap.get(cv2.CAP_PROP_FRAME_COUNT):
                cap.set(cv2.CAP_PROP_POS_FRAMES, 0)

        ret, frame = cap.read()
        if not ret:
            print("[WARN] Frame read failed; retrying …")
            cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
            continue

        # ── detection ────────────────────────────────────────────────────────
        processed       = preprocess(frame)
        free, total     = draw_zones(frame, processed, spaces, sensitivity)

        # ── FPS ──────────────────────────────────────────────────────────────
        now   = time.time()
        fps   = 0.9 * fps + 0.1 * (1.0 / max(now - t_prev, 1e-6))
        t_prev = now

        # ── HUD ──────────────────────────────────────────────────────────────
        draw_status_bar(frame, free, total, sensitivity, fps, debug_mode)

        cv2.imshow(WIN_MAIN, frame)

        if debug_mode:
            cv2.imshow(WIN_DEBUG, draw_debug_overlay(processed, spaces, sensitivity))
        else:
            cv2.destroyWindow(WIN_DEBUG) if cv2.getWindowProperty(
                WIN_DEBUG, cv2.WND_PROP_VISIBLE) >= 1 else None

        # ── keyboard ─────────────────────────────────────────────────────────
        key = cv2.waitKey(10) & 0xFF

        if key in (ord("q"), 27):
            break

        elif key == ord("d"):
            debug_mode = not debug_mode
            print(f"[DEBUG] {'ON' if debug_mode else 'OFF'}")

        elif key == ord("+") or key == ord("="):
            sensitivity = min(sensitivity + 10, 9999)
            print(f"[SENS ↑] {sensitivity}")

        elif key == ord("-"):
            sensitivity = max(sensitivity - 10, 1)
            print(f"[SENS ↓] {sensitivity}")

        elif key == ord("s"):
            save_sensitivity(cfg, sensitivity)

    cap.release()
    cv2.destroyAllWindows()
    print("[EXIT] Detector stopped.")


# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    main()
